# Generated by Django 2.2.16 on 2022-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
