# Generated by Django 2.2.16 on 2022-05-02 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20220502_2152'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='score_one',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'score')},
        ),
    ]
